### ISSUE TITLE
Could you add a LBY indecator and angle indicator

### ISSUE THREAD

**Issue by mint-xoxo** [L1nuxDotFun/space-hook#1]
yes

**Comment by w3bn00b** [comment]
later

**Comment by mint-xoxo** [comment]
okay

**Comment by koutsie** [comment]
@mint-xoxo sure

_Sent from my Nokia 6 using [FastHub-Libre](https://github.com/thermatk/FastHub-Libre/)_

**Comment by KNO56** [comment]
yes good meme

**Comment by xDyln** [comment]
closed due to cleaning up issues.
