### ISSUE TITLE
definetly needs a nicer menu

### ISSUE THREAD

**Issue by koutsie** [L1nuxDotFun/space-hook#2]
paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it paste it

**Comment by FilipeSilvens** [comment]
i agree 100%
