### ISSUE TITLE
Crash When Using Autowall

### ISSUE THREAD

**Issue by MinecraftBoy2009** [L1nuxDotFun/space-hook#5]
When i use autowall i crash

**Comment by koutsie** [comment]
Try debugging?

**Comment by Senpaicat** [comment]
Thread 1 "csgo_linux64" received signal SIGABRT, Aborted.
0x00007fdda9fad428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	in ../sysdeps/unix/sysv/linux/raise.c
