### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by doonayy** [L1nuxDotFun/space-hook#9]
Hi I'm the linux normie and it doesn't work.
Let me explain, everything is doing well, I download the cheat using : 
git clone ...
then 
sudo pacman -S ... (the needed depedencies)...
cd space-hook
then 
./build 
then after launching csgo 
./load 
"injected succesfully..."
Then I go in csgo press insert multiple time, nothing, i launch a game with bots, nothing.
I have the same issue with fuzion.
I'm on arch, I use -novid and -insecure as launch option.
After launching csgo and not loading the cheat but loading debug script, my game crash until I close the terminal window. 

I do get this in my console : 

[hm.txt](https://github.com/L1nuxDotFun/space-hook/files/3229362/hm.txt)

thank you, very much and sorry for my english I'm french.

**Comment by xDyln** [comment]
hmm add me on discord  :xDylan#0376  i can try help there, we can speak English or french i don't mind
